### ISSUE TITLE
onset/offset are shifting

### ISSUE THREAD

**Issue by robinmeier** [timsainb/vocalization-segmentation#3]
Hi Tim, when running continuity_segmentation-canary.ipynb on my own data, the onsets and offsets get slowly shifted to the right in my timeline. If you visualize results["onsets"] and "offsets" in audacity for example, you can see that in the beginning the segmentation is correct, but that towards the end (5' into my file) all the labels are off by about 600ms. see screenshot here: https://www.dropbox.com/s/2bmscg9rfptxpp3/ending_shifted.png?dl=0 and https://www.dropbox.com/s/p13mcnkbvbrm482/beginning_ok.png?dl=0
datafile https://www.dropbox.com/s/6x2jrenumi8xmyj/mediummocking001-v2.txt?dl=0
can send you audio on request.

**Comment by robinmeier** [comment]
ps: strangely the visualisation in the notebook seems to be correct.

**Comment by timsainb** [comment]
That's no good! I'll look into that (probably not till next week though). It looks like there's some bug related to how the sampling rate is computed for the spectrogram, since the segment boundaries are determined from the spectrogram.

**Comment by swasun** [comment]
@timsainb Hello, any updates please?

**Comment by timsainb** [comment]
Sorry, it might take a bit longer to get around to this than I thought.

**Comment by robinmeier** [comment]
Hi Tim, my friend Leo found the lines that create the offset 

win_length = n_fft if win_length_ms is None else int(win_length_ms / 1000 * rate)

hop_length = win_length // 4 if hop_length_ms is None else int(hop_length_ms / 1000 * rate)

it occurs when hop_length_ms * rate  isn’t a multiple of 1000

**Comment by robinmeier** [comment]
those lines are in vocalseg/dynamic_thresholding.py
and also in avgn/signalprocessing/spectrogramming.py

**Comment by timsainb** [comment]
Hey @robinmeier, I don't see those lines in this repo. Could you give me a line #? And would someone mind sending me a colab notebook of a .wav file where this issue occurs? Sorry again for the slow response, things are a bit hectic at the moment.

**Comment by timsainb** [comment]
Or just the .wav

**Comment by qsdfo** [comment]
Hi Tim,

I'm Leo, working with Robin. 
FIrst of all thanks a lot for the code! :)
Everything was so well documented and clear. It helped us a lot!!

Regarding the shifting issue, I think the problem comes from a mismatch between the hop_size used to compute the stft and the fft_rate used to set the markers.

l.80 in vocalseg/utils.py (https://github.com/timsainb/vocalization-segmentation/blob/bf11a1f0008566ee15033a20df5d49ae1d8d2e19/vocalseg/utils.py#L76)
where hop_length has to be rounded to be in nulber of samples
**hop_length=int(hop_length_ms / 1000 * fs)**

but in vocalseg/dynamic_thresholding.py (https://github.com/timsainb/vocalization-segmentation/blob/bf11a1f0008566ee15033a20df5d49ae1d8d2e19/vocalseg/dynamic_thresholding.py#L102), fft_rate uses not rounded values
**fft_rate = 1000 / hop_length_ms**

So if fs * hop_length_ms / 1000 is not an int, rounding introduces the shifting (typically with hop_length_ms = 2 and fs = 44100 hop_length is 88 samples, but fft_rate corresponds to 88.2 samples).

I think an easy fix would be to take the rounding into consideration when computing fft_rate (but I didn't try this!! I ended up using scipy stft which return time_bins in seconds).
So that would be
fft_rate = fs / int(hop_length_ms / 1000 * fs)

Best,
Léo

**Comment by timsainb** [comment]
Thanks Leo.

I made a PR to fix this and added a notebook with the example file that @robinmeier sent to make sure everything works properly. https://github.com/timsainb/vocalization-segmentation/pull/4

Let me know if you'd rather that file wasn't hosted on here, and I can update the PR to remove that file. 

Best,
Tim
